"""
Country Assessment list

"""

COUNTRY_LIST = [
    {
        'country_name': 'Afghanistan',
        'preferred_name': 'Afghanistan',
        'iso3': 'AFG',
        'iso2': 'AF',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'MENA',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,5)
    },
    {
        'country_name': 'Angola',
        'preferred_name': 'Angola',
        'iso3': 'AGO',
        'iso2': 'AO',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Bangladesh',
        'preferred_name': 'Bangladesh',
        'iso3': 'BGD',
        'iso2': 'BD',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'S&SE Asia',
        # 'coverage_4G': 70,
        'pop_density_km2': 500,
        'settlement_size': 500,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Bhutan',
        'preferred_name': 'Bhutan',
        'iso3': 'BTN',
        'iso2': 'BT',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'S&SE Asia',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,3)
    },
    {
        'country_name': 'Cameroon',
        'preferred_name': 'Cameroon',
        'iso3': 'CMR',
        'iso2': 'CM',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        # 'coverage_4G': 70,
        'pop_density_km2': 500,
        'settlement_size': 500,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Costa Rica',
        'preferred_name': 'Costa Rica',
        'iso3': 'CRI',
        'iso2': 'CR',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'LAC',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Egypt',
        'preferred_name': 'Egypt',
        'iso3': 'EGY',
        'iso2': 'EG',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'MENA',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,7)
    },
    {
        'country_name': 'El Salvador',
        'preferred_name': 'El Salvador',
        'iso3': 'SLV',
        'iso2': 'SV',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'LAC',
        'coverage_4G': 70,
        'pop_density_km2': 500,
        'settlement_size': 500,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,4)
    },
    {
        'country_name': 'Gambia (the)',
        'preferred_name': 'The Gambia',
        'iso3': 'GMB',
        'iso2': 'GM',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 0,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,3.5)
    },
    {
        'country_name': 'Honduras',
        'preferred_name': 'Honduras',
        'iso3': 'HND',
        'iso2': 'HN',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'LAC',
        'coverage_4G': 70,
        'pop_density_km2': 500,
        'settlement_size': 500,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,4.5)
    },
    {
        'country_name': 'India',
        'preferred_name': 'India',
        'iso3': 'IND',
        'iso2': 'IN',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'S&SE Asia',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Kenya',
        'preferred_name': 'Kenya',
        'iso3': 'KEN',
        'iso2': 'KE',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        'coverage_4G': 70,
        'pop_density_km2': 500,
        'settlement_size': 500,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Sri Lanka',
        'preferred_name': 'Sri Lanka',
        'iso3': 'LKA',
        'iso2': 'LK',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'S&SE Asia',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Morocco',
        'preferred_name': 'Morocco',
        'iso3': 'MAR',
        'iso2': 'MA',
        'regional_level': 3,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'MENA',
        'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,6)
    },
    {
        'country_name': 'Madagascar',
        'preferred_name': 'Madagascar',
        'iso3': 'MDG',
        'iso2': 'MG',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Maldives (the)',
        'preferred_name': 'The Maldives',
        'iso3': 'MDV',
        'iso2': 'MV',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'S&SE Asia',
        'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Mozambique',
        'preferred_name': 'Mozambique',
        'iso3': 'MOZ',
        'iso2': 'MZ',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Malawi',
        'preferred_name': 'Malawi',
        'iso3': 'MWI',
        'iso2': 'MW',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,8)
    },
    {
        'country_name': 'Nigeria',
        'preferred_name': 'Nigeria',
        'iso3': 'NGA',
        'iso2': 'NG',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,6)
    },
    {
        'country_name': 'Nepal',
        'preferred_name': 'Nepal',
        'iso3': 'NPL',
        'iso2': 'NP',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'S&SE Asia',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,4)
    },
    {
        'country_name': 'Pakistan',
        'preferred_name': 'Pakistan',
        'iso3': 'PAK',
        'iso2': 'PK',
        'regional_level': 2,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'S&SE Asia',
        # 'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,6)
    },
    {
        'country_name': 'Senegal',
        'preferred_name': 'Senegal',
        'iso3': 'SEN',
        'iso2': 'SN',
        'regional_level': 3,
        'core_node_level': 1,
        'regional_node_level': 2,
        'region': 'SSA',
        'coverage_4G': 70,
        'pop_density_km2': 100,
        'settlement_size': 200,
        'core_node_size': 2000,
        'subs_growth_low': 2,
        'sp_growth_low_urban': 2,
        'sp_growth_low_rural': 2,
        'subs_growth_baseline': 4,
        'sp_growth_baseline_urban': 4,
        'sp_growth_baseline_rural': 4,
        'subs_growth_high': 6,
        'sp_growth_high_urban': 6,
        'sp_growth_high_rural': 6,
        'phone_ownership_male': 50,
        'phone_ownership_female': 50,
        'figsize':(9,6)
    },
]


COUNTRY_PARAMETERS = {
    'AFG': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 6,
            'medium': 4,
            'low': 2,
        },
        'networks': { #38 million population
            'baseline_urban': 4,
            'baseline_suburban': 4,
            'baseline_rural': 4,
            'shared_urban': 4,
            'shared_suburban': 4,
            'shared_rural': 1,
        },
        'frequencies': {
            #https://developingtelecoms.com/telecom-business/telecom-regulation/11109-new-4g-auctions-on-the-way-in-afghanistan.html
            '3G': [
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ]
        },
        'financials': {
            'wacc': 15, #assumption
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.3,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.2,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 20,
            'tax_high': 45,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'AGO': {
        #https://en.wikipedia.org/wiki/List_of_mobile_network_operators_of_the_Middle_East_and_Africa#Angola
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 20,
            'medium': 17,
            'low': 14,
        },
        'networks': {
            'baseline_urban': 2,
            'baseline_suburban': 2,
            'baseline_rural': 2,
            'shared_urban': 2,
            'shared_suburban': 2,
            'shared_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 900,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ]
        },
        'financials': {
            'wacc': 9.5, #http://www.waccexpert.com/
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.3, #refine
            'spectrum_capacity_baseline_usd_mhz_pop': 0.2,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 25,
            'tax_high': 45,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'BGD': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 4,
            'medium': 3,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 4,
            'baseline_suburban': 4,
            'baseline_rural': 4,
            'srn_urban': 4,
            'srn_suburban': 4,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 900,
                    'bandwidth': '2x5',
                    # 'status': 'active',
                },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x5',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 10,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 32.5,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'BTN': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 10,
            'medium': 8,
            'low': 6,
        },
        'networks': {
            'baseline_urban': 2,
            'baseline_suburban': 2,
            'baseline_rural': 2,
            'srn_urban': 2,
            'srn_suburban': 2,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 850,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 10,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'CMR': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 9,
            'medium': 7,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'CRI': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 30,
            'medium': 26,
            'low': 20,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'shared_urban': 3,
            'shared_suburban': 3,
            'shared_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 850,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ]
        },
        'financials': {
            'wacc': 9.5, #http://www.waccexpert.com/
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.3, #refine
            'spectrum_capacity_baseline_usd_mhz_pop': 0.2,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 45,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'EGY': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 6,
            'medium': 4,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'SLV': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 25,
            'medium': 20,
            'low': 15,
        },
        'networks': {
            'baseline_urban': 4,
            'baseline_suburban': 4,
            'baseline_rural': 4,
            'srn_urban': 4,
            'srn_suburban': 4,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 1900,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 850,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.1,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.08,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'GMB': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 18,
            'medium': 15,
            'low': 12,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'shared_urban': 3,
            'shared_suburban': 3,
            'shared_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 900,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ]
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.03,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.02,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 31,
            'tax_high': 45,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'HND': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 16,
            'medium': 14,
            'low': 10,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 850,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 1700,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.2,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'IND': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 8,
            'medium': 4,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'KEN': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 10,
            'medium': 8,
            'low': 4,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                {
                    'frequency': 800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'LKA': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 6,
            'medium': 4,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 2,
            'baseline_suburban': 2,
            'baseline_rural': 2,
            'srn_urban': 2,
            'srn_suburban': 2,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'MAR': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 12,
            'medium': 10,
            'low': 6,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'MDG': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 6,
            'medium': 3,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 4,
            'baseline_suburban': 4,
            'baseline_rural': 4,
            'srn_urban': 4,
            'srn_suburban': 4,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'MDV': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 35,
            'medium': 30,
            'low': 25,
        },
        'networks': {
            'baseline_urban': 2,
            'baseline_suburban': 2,
            'baseline_rural': 2,
            'srn_urban': 2,
            'srn_suburban': 2,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'MOZ': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 8,
            'medium': 4,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 2,
            'baseline_suburban': 2,
            'baseline_rural': 2,
            'srn_urban': 2,
            'srn_suburban': 2,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'MWI': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 8,
            'medium': 4,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'NGA': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 8,
            'medium': 6,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 4,
            'baseline_suburban': 4,
            'baseline_rural': 4,
            'srn_urban': 4,
            'srn_suburban': 4,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'NPL': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 6,
            'medium': 4,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'PAK': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 6,
            'medium': 4,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 4,
            'baseline_suburban': 4,
            'baseline_rural': 4,
            'srn_urban': 4,
            'srn_suburban': 4,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    'SEN': {
        'luminosity': {
            'high': 5,
            'medium': 1,
        },
        'arpu': {
            'high': 8,
            'medium': 6,
            'low': 2,
        },
        'networks': {
            'baseline_urban': 3,
            'baseline_suburban': 3,
            'baseline_rural': 3,
            'srn_urban': 3,
            'srn_suburban': 3,
            'srn_rural': 1,
        },
        'frequencies': {
            '3G': [
                # {
                #     'frequency': 1800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 2100,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '4G': [
                # {
                #     'frequency': 800,
                #     'bandwidth': '2x10',
                #     # 'status': 'active',
                # },
                {
                    'frequency': 1800,
                    'bandwidth': '2x10',
                    # 'status': 'active',
                },
            ],
            '5G': [
                {
                    'frequency': 700,
                    'bandwidth': '2x10',
                    # 'status': 'inactive',
                },
                {
                    'frequency': 3500,
                    'bandwidth': ' 1x40',
                    # 'status': 'inactive',
                },
            ],
        },
        'financials': {
            'wacc': 15,
            'profit_margin': 20,
            'spectrum_coverage_baseline_usd_mhz_pop': 0.04,
            'spectrum_capacity_baseline_usd_mhz_pop': 0.03,
            'spectrum_cost_low': 25,
            'spectrum_cost_high': 200,
            'tax_low': 10,
            'tax_baseline': 30,
            'tax_high': 40,
            'administration_percentage_of_network_cost': 20,
            },
        },
    }
